// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy4J3NEi7JrQ2YYfyMPuo-kVcoUvqlyhQ',
    appId: '1:20688031913:web:42d0a5e79b6d009bc419b8',
    messagingSenderId: '20688031913',
    projectId: 'social-media-d687b',
    authDomain: 'social-media-d687b.firebaseapp.com',
    storageBucket: 'social-media-d687b.appspot.com',
    measurementId: 'G-SPMXK9B0QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkH7qVN_ZTWdpTZtaXO_pIdRJUkWQpu5A',
    appId: '1:20688031913:android:dbd1e6d273330d3ac419b8',
    messagingSenderId: '20688031913',
    projectId: 'social-media-d687b',
    storageBucket: 'social-media-d687b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTObUBQEhsSjaAfsU17PWYbp5egfsgSQ',
    appId: '1:20688031913:ios:26a7027f542c1a8bc419b8',
    messagingSenderId: '20688031913',
    projectId: 'social-media-d687b',
    storageBucket: 'social-media-d687b.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWTObUBQEhsSjaAfsU17PWYbp5egfsgSQ',
    appId: '1:20688031913:ios:ab692b6413b862e0c419b8',
    messagingSenderId: '20688031913',
    projectId: 'social-media-d687b',
    storageBucket: 'social-media-d687b.appspot.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
